name: Schedule Build

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # every 30min UTC

jobs:
  build:
    name: Schedule Build
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:11-mvn3

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress